# Generated by Django 6.0.3 on 2026-04-09 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Brand Name')),
                ('origin', models.CharField(max_length=50, verbose_name='Country')),
                ('manufacturing_since', models.IntegerField(verbose_name='Manufacturing Since')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('launch_date', models.DateField(verbose_name='Launch Date')),
                ('platform', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('Others', 'Others')], max_length=50, verbose_name='Platform')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='PhoneReview.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Phone Model',
                'verbose_name_plural': 'Phone Models',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Rating(1-5)')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Dislikes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('phone_models', models.ManyToManyField(related_name='reviews', to='PhoneReview.phonemodel', verbose_name='Related Phone Models')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=50, verbose_name='Username')),
                ('text', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Posted At')),
                ('review_detail.html', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='PhoneReview.review_detail.html', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
