# Generated by Django 6.0.3 on 2026-04-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='newslink',
            field=models.URLField(blank=True, help_text='External link for news or reviews', verbose_name='News Link'),
        ),
    ]
