# Generated by Django 6.0.3 on 2026-04-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0002_phonemodel_newslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='image_url',
            field=models.URLField(blank=True, help_text='手机型号图片', verbose_name='Image URL'),
        ),
    ]
