# Generated by Django 6.0.3 on 2026-03-25 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='品牌名称')),
                ('origin', models.CharField(max_length=50, verbose_name='所属国家')),
                ('logo_url', models.URLField(blank=True, help_text='可以填一个网上的图片地址', verbose_name='Logo链接')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌管理',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='型号名称')),
                ('launch_date', models.DateField(verbose_name='发布日期')),
                ('os_type', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('Others', '其他')], max_length=50, verbose_name='操作系统')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='reviews.brand', verbose_name='所属品牌')),
            ],
            options={
                'verbose_name': '手机型号',
                'verbose_name_plural': '手机型号管理',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='测评标题')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='评分(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL别名')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('phones', models.ManyToManyField(related_name='reviews', to='reviews.phonemodel', verbose_name='关联手机')),
            ],
            options={
                'verbose_name': '手机测评',
                'verbose_name_plural': '测评文章管理',
            },
        ),
    ]
