# Generated by Django 6.0.3 on 2026-03-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_dislikes_review_likes_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'verbose_name': 'Phone Model', 'verbose_name_plural': 'Phone Models'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='origin',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Posted At'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=50, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='reviews.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='launch_date',
            field=models.DateField(verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='os_type',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('Others', 'Others')], max_length=50, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='review',
            name='phones',
            field=models.ManyToManyField(related_name='reviews', to='reviews.phonemodel', verbose_name='Related Phones'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, verbose_name='Rating(1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
