# Generated by Django 6.0.3 on 2026-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, help_text='游戏图片URL'),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='评分 0.0-10.0', max_digits=3),
        ),
    ]
